name: Run Playwright Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Linting
        run: yarn lint

      - name: Prettier
        run: yarn prettier:check

      - name: Install Playwright
        run: yarn playwright install

      - name: Run tests
        run: yarn allTestsHeadless
        continue-on-error: true

  upload-test-report:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: PlaywrightTask/e2e-test-report

      - name: workspace
        run: find ../ -print
